-- SELECT CITY,COUNTRY FROM CITY
-- LEFT JOIN COUNTRY ON COUNTRY.COUNTRY_ID = CITY.CITY_ID;

--  SELECT PAYMENT_ID,FIRST_NAME,LAST_NAME FROM PAYMENT
-- RIGHT JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=PAYMENT.PAYMENT_ID; 

 SELECT RENTAL_ID,FIRST_NAME,LAST_NAME FROM CUSTOMER
FULL JOIN RENTAL ON RENTAL.RENTAL_ID=CUSTOMER.CUSTOMER_ID; 


